In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("january.txt", delimiter='\t')

c:\users\int-hrathore\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\int-hrathore\appdata\local\programs\python\python36\lib\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
01-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
02-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
03-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
04-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
05-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>

06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
06-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
07-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>
08-01-1999 <class 'str'>

In [123]:
df

,vru+line,call_id,customer_id,priority,type,date,vru_entry,vru_exit,vru_time,q_start,q_exit,q_time,outcome,ser_start,ser_exit,ser_time,server
0,AA0101,33116,9664491.0,2,PS,1999-01-01,0:00:31,0:00:36,5,0:00:36,0:03:09,153,HANG,0:00:00,0:00:00,0,NO_SERVER
1,AA0101,33117,0.0,0,PS,1999-01-01,0:34:12,0:34:23,11,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
2,AA0101,33118,27997683.0,2,PS,1999-01-01,6:55:20,6:55:26,6,6:55:26,6:55:43,17,AGENT,6:55:43,6:56:37,54,MICHAL
3,AA0101,33119,0.0,0,PS,1999-01-01,7:41:16,7:41:26,10,0:00:00,0:00:00,0,AGENT,7:41:25,7:44:53,208,BASCH
4,AA0101,33120,0.0,0,PS,1999-01-01,8:03:14,8:03:24,10,0:00:00,0:00:00,0,AGENT,8:03:23,8:05:10,107,MICHAL
5,AA0101,33121,0.0,0,PS,1999-01-01,8:18:42,8:18:51,9,0:00:00,0:00:00,0,AGENT,8:18:50,8:23:25,275,KAZAV
6,AA0101,33122,0.0,0,PS,1999-01-01,8:28:33,8:28:43,10,0:00:00,0:00:00,0,AGENT,8:28:42,8:30:24,102,KAZAV
7,AA0101,33123,68062744.0,2,PS,1999-01-01,8:42:13,8:42:19,6,8:42:19,8:42:23,4,AGENT,8:42:23,8:45:30,187,KAZAV
8,AA0101,33124,0.0,0,PS,1999-01-01,8:52:52,8:53:06,14,0:00:00,0:00:00,0,AGENT,8:53:05,8:54:38,93,BASCH
9,AA0101,33125,1466671.0,2,PS,1999-01-01,9:04:04,9:04:10,6,9:04:10,9:04:56,46,AGENT,9:04:54,9:06:37,103,VICKY
10,AA0101,33126,0.0,0,PS,1999-01-01,9:16:49,9:17:20,31,0:00:00,0:00:00,0,AGENT,9:17:19,9:18:27,68,YITZ
11,AA0101,33127,23949225.0,2,PS,1999-01-01,9:27:03,9:27:09,6,9:27:09,9:28:00,51,AGENT,9:27:58,9:31:13,195,SHARON
12,AA0101,33128,59669259.0,1,PS,1999-01-01,9:41:14,9:41:20,6,9:41:20,9:41:46,26,AGENT,9:41:45,9:42:19,34,BASCH
13,AA0101,33129,49921232.0,2,PS,1999-01-01,9:47:49,9:47:55,6,9:47:55,9:49:15,80,AGENT,9:49:14,9:51:48,154,KAZAV
14,AA0101,33130,0.0,0,PS,1999-01-01,10:04:47,10:04:56,9,0:00:00,0:00:00,0,AGENT,10:04:56,10:05:49,53,MORIAH
15,AA0101,33131,0.0,0,PS,1999-01-01,10:23:44,10:23:54,10,0:00:00,0:00:00,0,AGENT,10:23:53,10:27:47,234,VICKY
16,AA0101,33132,0.0,0,PS,1999-01-01,10:35:08,10:35:28,20,0:00:00,0:00:00,0,AGENT,10:35:26,10:36:19,53,BASCH
17,AA0101,33133,24290983.0,2,PS,1999-01-01,10:48:44,10:48:49,5,10:48:49,10:49:17,28,AGENT,10:49:17,11:01:22,725,BASCH
18,AA0101,33134,0.0,0,PS,1999-01-01,11:07:30,11:07:38,8,0:00:00,0:00:00,0,AGENT,11:07:43,11:07:46,3,NO_SERVER
19,AA0101,33135,0.0,0,PS,1999-01-01,11:23:55,11:24:04,9,0:00:00,0:00:00,0,AGENT,11:24:03,11:24:55,52,YITZ
20,AA0101,33136,50698984.0,2,PS,1999-01-01,11:35:18,11:35:23,5,11:35:23,11:36:15,52,AGENT,11:36:15,11:38:14,119,BASCH
21,AA0101,33137,0.0,0,PS,1999-01-01,11:49:27,11:49:38,11,0:00:00,0:00:00,0,AGENT,11:49:37,11:49:48,11,VICKY
22,AA0101,33138,0.0,0,PS,1999-01-01,12:09:22,12:09:32,10,0:00:00,0:00:00,0,AGENT,12:09:31,12:10:58,87,YITZ
23,AA0101,33139,0.0,0,NW,1999-01-01,12:25:30,12:25:43,13,0:00:00,0:00:00,0,AGENT,12:25:42,12:26:08,26,YITZ
24,AA0101,33140,0.0,0,PS,1999-01-01,12:49:43,12:49:56,13,0:00:00,0:00:00,0,AGENT,12:49:56,12:56:18,382,VICKY
25,AA0101,33141,27347905.0,1,PS,1999-01-01,13:12:08,13:12:13,5,13:12:13,13:14:05,112,HANG,0:00:00,0:00:00,0,NO_SERVER
26,AA0101,33142,0.0,0,PS,1999-01-01,13:34:28,13:34:38,10,0:00:00,0:00:00,0,AGENT,13:34:37,13:37:22,165,ZOHARI
27,AA0101,33143,0.0,0,PS,1999-01-01,13:49:47,13:49:57,10,0:00:00,0:00:00,0,AGENT,13:49:56,13:52:43,167,VICKY
28,AA0101,33144,0.0,0,PS,1999-01-01,14:07:17,14:07:34,17,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
29,AA0101,33146,0.0,0,PE,1999-01-01,14:43:10,14:43:10,0,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31569,AA0216,5435,0.0,0,IN,1999-01-25,11:17:13,11:17:22,9,11:17:22,11:20:47,205,AGENT,11:20:46,11:22:34,108,YIFAT
31570,AA0216,5436,0.0,0,IN,1999-01-25,13:53:28,13:53:36,8,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31571,AA0216,5437,0.0,0,IN,1999-01-25,16:11:19,16:11:28,9,16:11:28,16:15:35,247,HANG,0:00:00,0:00:00,0,NO_SERVER
31572,AA0216,5438,0.0,0,IN,1999-01-25,17:41:43,17:41:53,10,17:41:53,17:43:23,90,AGENT,17:43:22,17:43:53,31,ANAT
31573,AA0216,5439,0.0,0,IN,1999-01-26,8:59:38,8:59:47,9,8:59:47,9:00:05,18,AGENT,9:00:04,9:03:02,178,YIFAT
31574,AA0216,5440,0.0,0,IN,1999-01-26,10:01:24,10:01:29,5,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31575,AA0216,5441,0.0,0,IN,1999-01-26,10:02:26,10:02:31,5,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31576,AA0216,5442,0.0,0,IN,1999-01-26,11:01:18,11:01:31,13,0:00:00,0:00:00,0,AGENT,11:01:30,11:02:26,56,SHARON
31577,AA0216,5443,0.0,0,IN,1999-01-26,13:23:18,13:23:27,9,13:23:27,13:23:49,22,AGENT,13:23:48,13:38:04,856,YIFAT
31578,AA0216,5444,0.0,0,IN,1999-01-26,14:36:40,14:36:50,10,14:36:50,14:39:51,181,AGENT,14:39:50,14:45:39,349,YIFAT
31579,AA0216,5445,0.0,0,IN,1999-01-26,19:37:41,19:37:50,9,19:37:50,19:38:41,51,HANG,0:00:00,0:00:00,0,NO_SERVER
31580,AA0216,5446,0.0,0,IN,1999-01-26,21:10:01,21:10:10,9,0:00:00,0:00:00,0,AGENT,21:10:19,21:10:26,7,NO_SERVER
31581,AA0216,5447,0.0,0,IN,1999-01-27,8:35:59,8:36:09,10,8:36:09,8:37:34,85,AGENT,8:37:33,8:38:32,59,MICHAL
31582,AA0216,5448,0.0,0,IN,1999-01-27,14:52:05,14:52:20,15,0:00:00,0:00:00,0,AGENT,14:52:18,15:01:42,564,MICHAL
31583,AA0216,5449,0.0,0,IN,1999-01-27,16:22:24,16:22:38,14,0:00:00,0:00:00,0,AGENT,16:22:38,16:23:50,72,YIFAT
31584,AA0216,5450,0.0,0,IN,1999-01-27,17:34:31,17:34:40,9,17:34:40,17:37:18,158,AGENT,17:37:17,17:40:01,164,ANAT
31585,AA0216,5451,0.0,0,IN,1999-01-27,18:15:59,18:16:12,13,0:00:00,0:00:00,0,AGENT,18:16:12,18:18:21,129,YIFAT
31586,AA0216,5452,0.0,0,IN,1999-01-29,11:18:23,11:18:40,17,0:00:00,0:00:00,0,AGENT,11:18:40,11:21:22,162,ANAT
31587,AA0216,5453,0.0,0,IN,1999-01-29,23:05:37,23:05:45,8,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31588,AA0216,5454,0.0,0,IN,1999-01-31,9:12:10,9:12:13,3,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31589,AA0216,5455,0.0,0,IN,1999-01-31,9:33:50,9:33:59,9,9:33:59,9:34:38,39,HANG,0:00:00,0:00:00,0,NO_SERVER
31590,AA0216,5456,0.0,0,IN,1999-01-31,11:26:25,11:26:34,9,11:26:34,11:31:20,286,HANG,0:00:00,0:00:00,0,NO_SERVER
31591,AA0216,5457,0.0,0,IN,1999-01-31,12:11:09,12:11:18,9,12:11:18,12:13:13,115,AGENT,12:13:12,12:38:05,1493,YITZ
31592,AA0216,5458,0.0,0,IN,1999-01-31,13:13:21,13:13:28,7,0:00:00,0:00:00,0,HANG,0:00:00,0:00:00,0,NO_SERVER
31593,AA0216,5459,0.0,0,IN,1999-01-31,14:03:32,14:03:51,19,0:00:00,0:00:00,0,AGENT,14:03:50,14:07:01,191,TOVA
31594,AA0216,5460,0.0,0,IN,1999-01-31,14:05:51,14:06:00,9,14:06:00,14:11:08,308,AGENT,14:09:59,14:13:08,189,TOVA
31595,AA0216,5461,0.0,0,IN,1999-01-31,16:55:02,16:55:14,12,0:00:00,0:00:00,0,AGENT,16:55:13,17:02:04,411,YIFAT
31596,AA0216,5462,0.0,0,IN,1999-01-31,21:59:43,22:00:01,18,0:00:00,0:00:00,0,AGENT,22:00:00,22:03:11,191,MICHAL
31597,AA0216,5463,0.0,0,IN,1999-01-31,23:22:59,23:23:09,10,23:23:09,23:24:16,67,AGENT,23:24:15,23:26:04,109,BENSION
31598,AA0216,5464,0.0,0,IN,1999-01-31,23:26:18,23:26:27,9,23:26:27,23:26:44,17,AGENT,23:26:43,23:27:45,62,BENSION

In [124]:
MICHAL_df = df[df['server'] == 'MICHAL']
MICHAL_df

,vru+line,call_id,customer_id,priority,type,date,vru_entry,vru_exit,vru_time,q_start,q_exit,q_time,outcome,ser_start,ser_exit,ser_time,server
2,AA0101,33118,27997683.0,2,PS,1999-01-01,6:55:20,6:55:26,6,6:55:26,6:55:43,17,AGENT,6:55:43,6:56:37,54,MICHAL
4,AA0101,33120,0.0,0,PS,1999-01-01,8:03:14,8:03:24,10,0:00:00,0:00:00,0,AGENT,8:03:23,8:05:10,107,MICHAL
32,AA0101,33149,0.0,0,PS,1999-02-01,19:28:05,19:28:13,8,0:00:00,0:00:00,0,AGENT,19:28:12,19:32:53,281,MICHAL
33,AA0101,33150,0.0,0,PS,1999-02-01,19:46:58,19:47:07,9,0:00:00,0:00:00,0,AGENT,19:47:06,19:49:54,168,MICHAL
39,AA0101,33156,0.0,0,PS,1999-02-01,22:39:42,22:39:51,9,0:00:00,0:00:00,0,AGENT,22:39:50,22:40:44,54,MICHAL
41,AA0101,33158,29459021.0,1,PS,1999-02-01,23:42:18,23:42:24,6,23:42:24,23:42:48,24,AGENT,23:42:47,23:43:40,53,MICHAL
84,AA0101,33202,31764798.0,1,PS,1999-03-01,13:23:22,13:23:28,6,13:23:28,13:23:32,4,AGENT,13:23:31,13:24:17,46,MICHAL
129,AA0101,33248,22665004.0,1,PS,1999-04-01,8:49:26,8:49:33,7,8:49:33,8:49:37,4,AGENT,8:49:37,8:53:05,208,MICHAL
145,AA0101,33264,0.0,0,NW,1999-04-01,11:04:18,11:04:36,18,0:00:00,0:00:00,0,AGENT,11:04:34,11:04:42,8,MICHAL
147,AA0101,33266,24173163.0,2,PS,1999-04-01,11:15:00,11:15:05,5,11:15:05,11:15:52,47,AGENT,11:15:52,11:16:03,11,MICHAL
159,AA0101,33278,0.0,0,NW,1999-04-01,13:03:48,13:03:57,9,13:03:57,13:07:45,228,AGENT,13:07:44,13:09:12,88,MICHAL
170,AA0101,33289,641902.0,2,PS,1999-04-01,14:47:19,14:47:25,6,14:47:25,14:47:55,30,AGENT,14:47:55,14:48:42,47,MICHAL
269,AA0101,33388,0.0,0,NW,1999-05-01,16:34:37,16:34:46,9,16:34:46,16:35:00,14,AGENT,16:35:00,16:35:37,37,MICHAL
272,AA0101,33391,0.0,0,NW,1999-05-01,16:56:45,16:56:57,12,0:00:00,0:00:00,0,AGENT,16:56:56,16:57:33,37,MICHAL
274,AA0101,33393,0.0,0,NW,1999-05-01,17:16:36,17:16:48,12,0:00:00,0:00:00,0,AGENT,17:16:48,17:17:51,63,MICHAL
289,AA0101,33408,0.0,0,NW,1999-05-01,21:04:20,21:04:32,12,0:00:00,0:00:00,0,AGENT,21:04:32,21:07:19,167,MICHAL
293,AA0101,33412,0.0,0,PS,1999-05-01,22:25:01,22:25:09,8,0:00:00,0:00:00,0,AGENT,22:25:08,22:29:16,248,MICHAL
331,AA0101,33450,0.0,0,PS,1999-06-01,13:55:33,13:55:42,9,0:00:00,0:00:00,0,AGENT,13:55:41,13:57:00,79,MICHAL
332,AA0101,33451,1018456.0,2,PS,1999-06-01,14:03:51,14:03:56,5,14:03:56,14:04:01,5,AGENT,14:04:00,14:06:22,142,MICHAL
338,AA0101,33457,58440181.0,2,PS,1999-06-01,15:12:47,15:12:52,5,15:12:52,15:14:51,119,AGENT,15:14:50,15:16:00,70,MICHAL
341,AA0101,33460,0.0,0,NW,1999-06-01,15:43:41,15:43:51,10,15:43:51,15:43:54,3,AGENT,15:43:54,15:44:54,60,MICHAL
344,AA0101,33463,313749442.0,1,PE,1999-06-01,16:19:15,16:19:19,4,16:19:19,16:20:18,59,AGENT,16:20:16,16:20:22,6,MICHAL
350,AA0101,33469,54155254.0,2,PS,1999-06-01,17:42:09,17:42:15,6,17:42:15,17:42:23,8,AGENT,17:42:22,17:44:07,105,MICHAL
358,AA0101,33477,0.0,0,NW,1999-06-01,19:46:11,19:46:21,10,19:46:21,19:46:28,7,AGENT,19:46:28,19:46:51,23,MICHAL
359,AA0101,33478,0.0,0,PS,1999-06-01,20:10:42,20:10:57,15,0:00:00,0:00:00,0,AGENT,20:10:56,20:16:20,324,MICHAL
373,AA0101,33492,42445916.0,2,PS,1999-07-01,8:23:22,8:23:28,6,8:23:28,8:25:03,95,AGENT,8:25:02,8:26:23,81,MICHAL
379,AA0101,33498,3519998.0,2,PS,1999-07-01,9:14:32,9:14:38,6,9:14:38,9:15:34,56,AGENT,9:15:33,9:18:09,156,MICHAL
386,AA0101,33505,24851511.0,2,PS,1999-07-01,10:23:48,10:23:54,6,10:23:54,10:25:36,102,AGENT,10:25:35,10:27:00,85,MICHAL
394,AA0101,33513,0.0,0,PS,1999-07-01,11:42:24,11:42:32,8,0:00:00,0:00:00,0,AGENT,11:42:32,11:44:23,111,MICHAL
403,AA0101,33522,0.0,0,PS,1999-07-01,13:36:10,13:36:19,9,0:00:00,0:00:00,0,AGENT,13:36:18,13:41:09,291,MICHAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31395,AA0215,13058,0.0,0,PS,1999-01-30,20:24:32,20:24:41,9,0:00:00,0:00:00,0,AGENT,20:24:40,20:27:28,168,MICHAL
31427,AA0215,13091,0.0,0,PS,1999-01-31,14:30:02,14:30:12,10,0:00:00,0:00:00,0,AGENT,14:30:11,14:32:26,135,MICHAL
31446,AA0215,13110,0.0,0,NW,1999-01-31,18:24:47,18:25:04,17,0:00:00,0:00:00,0,AGENT,18:25:03,18:26:56,113,MICHAL
31451,AA0215,13115,0.0,0,PS,1999-01-31,20:25:57,20:26:12,15,0:00:00,0:00:00,0,AGENT,20:26:11,20:39:23,792,MICHAL
31453,AA0215,13117,0.0,0,PS,1999-01-31,21:38:45,21:38:56,11,0:00:00,0:00:00,0,AGENT,21:38:55,21:39:55,60,MICHAL
31458,AA0216,5324,0.0,0,IN,1999-01-01,9:58:06,9:58:37,31,0:00:00,0:00:00,0,AGENT,9:58:36,9:59:59,83,MICHAL
31460,AA0216,5326,0.0,0,IN,1999-01-01,10:46:12,10:46:22,10,10:46:22,10:46:45,23,AGENT,10:46:45,10:47:23,38,MICHAL
31470,AA0216,5336,0.0,0,IN,1999-04-01,8:08:05,8:08:19,14,0:00:00,0:00:00,0,AGENT,8:08:18,8:11:56,218,MICHAL
31473,AA0216,5339,0.0,0,IN,1999-04-01,9:58:50,9:59:04,14,0:00:00,0:00:00,0,AGENT,9:59:03,10:03:30,267,MICHAL
31475,AA0216,5341,0.0,0,IN,1999-04-01,11:53:33,11:53:42,9,11:53:42,11:54:59,77,AGENT,11:54:58,11:56:44,106,MICHAL
31485,AA0216,5351,0.0,0,IN,1999-05-01,17:54:03,17:54:13,10,17:54:13,17:55:35,82,AGENT,17:55:35,18:01:38,363,MICHAL
31487,AA0216,5353,0.0,0,IN,1999-05-01,18:54:50,18:55:02,12,0:00:00,0:00:00,0,AGENT,18:55:02,18:57:31,149,MICHAL
31491,AA0216,5357,0.0,0,IN,1999-06-01,13:13:56,13:14:10,14,0:00:00,0:00:00,0,AGENT,13:14:09,13:35:31,1282,MICHAL
31492,AA0216,5358,0.0,0,IN,1999-06-01,14:28:17,14:28:27,10,14:28:27,14:28:56,29,AGENT,14:28:55,14:38:47,592,MICHAL
31494,AA0216,5360,0.0,0,IN,1999-07-01,8:15:09,8:15:25,16,0:00:00,0:00:00,0,AGENT,8:15:24,8:18:47,203,MICHAL
31495,AA0216,5361,0.0,0,IN,1999-07-01,10:21:57,10:22:06,9,10:22:06,10:24:51,165,AGENT,10:24:50,10:25:31,41,MICHAL
31497,AA0216,5363,0.0,0,IN,1999-07-01,10:31:51,10:32:01,10,10:32:01,10:34:00,119,AGENT,10:33:59,10:40:08,369,MICHAL
31515,AA0216,5381,0.0,0,IN,1999-10-01,17:21:34,17:21:43,9,17:21:43,17:22:54,71,AGENT,17:22:53,17:27:25,272,MICHAL
31522,AA0216,5388,0.0,0,IN,1999-01-13,16:55:07,16:55:17,10,16:55:17,16:59:40,263,AGENT,16:59:39,17:06:27,408,MICHAL
31530,AA0216,5396,0.0,0,IN,1999-01-17,15:52:22,15:52:37,15,0:00:00,0:00:00,0,AGENT,15:52:36,16:01:49,553,MICHAL
31532,AA0216,5398,0.0,0,IN,1999-01-17,16:37:06,16:37:15,9,16:37:15,16:39:24,129,AGENT,16:39:22,16:44:32,310,MICHAL
31537,AA0216,5403,0.0,0,IN,1999-01-18,16:18:34,16:18:43,9,16:18:43,16:22:02,199,AGENT,16:22:01,16:28:25,384,MICHAL
31539,AA0216,5405,0.0,0,IN,1999-01-18,16:52:57,16:53:06,9,16:53:06,16:57:45,279,AGENT,16:57:44,17:01:55,251,MICHAL
31544,AA0216,5410,0.0,0,IN,1999-01-19,19:14:49,19:14:59,10,19:14:59,19:17:26,147,AGENT,19:17:25,19:19:09,104,MICHAL
31552,AA0216,5418,0.0,0,IN,1999-01-21,10:59:59,11:00:09,10,11:00:09,11:03:37,208,AGENT,11:03:36,11:09:45,369,MICHAL
31558,AA0216,5424,0.0,0,IN,1999-01-22,9:20:01,9:20:15,14,0:00:00,0:00:00,0,AGENT,9:20:14,9:27:14,420,MICHAL
31559,AA0216,5425,0.0,0,IN,1999-01-22,12:30:26,12:30:35,9,12:30:35,12:31:57,82,AGENT,12:31:56,12:37:30,334,MICHAL
31581,AA0216,5447,0.0,0,IN,1999-01-27,8:35:59,8:36:09,10,8:36:09,8:37:34,85,AGENT,8:37:33,8:38:32,59,MICHAL
31582,AA0216,5448,0.0,0,IN,1999-01-27,14:52:05,14:52:20,15,0:00:00,0:00:00,0,AGENT,14:52:18,15:01:42,564,MICHAL
31596,AA0216,5462,0.0,0,IN,1999-01-31,21:59:43,22:00:01,18,0:00:00,0:00:00,0,AGENT,22:00:00,22:03:11,191,MICHAL

In [125]:
# Specialized form for finding agents mean handling time for A day

MICHAL_df[MICHAL_df['date'] == '01-01-1999']['ser_time'].mean()

162.50746268656715

In [126]:
dates = MICHAL_df['date'].unique()
print(dates)

['1999-01-01T00:00:00.000000000' '1999-02-01T00:00:00.000000000'
 '1999-03-01T00:00:00.000000000' '1999-04-01T00:00:00.000000000'
 '1999-05-01T00:00:00.000000000' '1999-06-01T00:00:00.000000000'
 '1999-07-01T00:00:00.000000000' '1999-10-01T00:00:00.000000000'
 '1999-01-13T00:00:00.000000000' '1999-01-15T00:00:00.000000000'
 '1999-01-17T00:00:00.000000000' '1999-01-22T00:00:00.000000000'
 '1999-01-27T00:00:00.000000000' '1999-01-30T00:00:00.000000000'
 '1999-01-31T00:00:00.000000000' '1999-01-18T00:00:00.000000000'
 '1999-01-19T00:00:00.000000000' '1999-01-20T00:00:00.000000000'
 '1999-01-21T00:00:00.000000000']

In [109]:
for date in dates:
    print(date,MICHAL_df[MICHAL_df['date'] == date]['ser_time'].mean())

01-01-1999 162.50746268656715
02-01-1999 116.28333333333333
03-01-1999 169.23076923076923
04-01-1999 110.39393939393939
05-01-1999 125.50549450549451
06-01-1999 155.77777777777777
07-01-1999 191.33009708737865
10-01-1999 143.23636363636365
13-01-1999 155.65289256198346
15-01-1999 113.05479452054794
17-01-1999 127.83783783783784
22-01-1999 185.3913043478261
27-01-1999 148.35555555555555
30-01-1999 159.45
31-01-1999 172.83908045977012
18-01-1999 142.01680672268907
19-01-1999 156.08490566037736
20-01-1999 161.13829787234042
21-01-1999 163.77319587628867